#!/usr/bin/env python3
"""Prints the Arabic joining table for source/lib/Bidi.bs from Unicode's
own data (Python's unicodedata): for each letter with presentation forms,
its isolated, final, initial, and medial forms, read from the
decompositions of U+FB50-FDFF and U+FE70-FEFF ("<final> 0628" is BEH's
final form). A letter with only isolated and final forms joins only to
the letter before it (right-joining, like ALEF); with all four it joins
both ways.

  python3 tools/arabic_forms.py
"""

import unicodedata

forms = {}
for cp in list(range(0xFB50, 0xFE00)) + list(range(0xFE70, 0xFF00)):
    d = unicodedata.decomposition(chr(cp)).split()
    if len(d) != 2 or d[0] not in ("<isolated>", "<final>", "<initial>", "<medial>"):
        continue
    base = int(d[1], 16)
    forms.setdefault(base, {}).setdefault(d[0][1:-1], cp)

print("    ' Generated by tools/arabic_forms.py: letter, isolated, final,")
print("    ' initial, medial (0: no such form).")
rows = []
for base in sorted(forms):
    f = forms[base]
    if "isolated" not in f and "final" not in f:
        continue
    rows.append("&h%04X, &h%04X, &h%04X, &h%04X, &h%04X" % (
        base, f.get("isolated", 0), f.get("final", 0), f.get("initial", 0), f.get("medial", 0)))
for i in range(0, len(rows), 2):
    print("        " + ", ".join(rows[i:i + 2]))
